// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: backend.proto

package opi_storage_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NVMfRemoteControllerConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerConnectRequest) Reset() {
	*x = NVMfRemoteControllerConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerConnectRequest) ProtoMessage() {}

func (x *NVMfRemoteControllerConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerConnectRequest.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerConnectRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0}
}

func (x *NVMfRemoteControllerConnectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerConnectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerConnectResponse) Reset() {
	*x = NVMfRemoteControllerConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerConnectResponse) ProtoMessage() {}

func (x *NVMfRemoteControllerConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerConnectResponse.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerConnectResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1}
}

func (x *NVMfRemoteControllerConnectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerConnectResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerDisconnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerDisconnectRequest) Reset() {
	*x = NVMfRemoteControllerDisconnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerDisconnectRequest) ProtoMessage() {}

func (x *NVMfRemoteControllerDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerDisconnectRequest.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{2}
}

func (x *NVMfRemoteControllerDisconnectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerDisconnectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerDisconnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerDisconnectResponse) Reset() {
	*x = NVMfRemoteControllerDisconnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerDisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerDisconnectResponse) ProtoMessage() {}

func (x *NVMfRemoteControllerDisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerDisconnectResponse.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerDisconnectResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{3}
}

func (x *NVMfRemoteControllerDisconnectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerDisconnectResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerResetRequest) Reset() {
	*x = NVMfRemoteControllerResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerResetRequest) ProtoMessage() {}

func (x *NVMfRemoteControllerResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerResetRequest.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerResetRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{4}
}

func (x *NVMfRemoteControllerResetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerResetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerResetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerResetResponse) Reset() {
	*x = NVMfRemoteControllerResetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerResetResponse) ProtoMessage() {}

func (x *NVMfRemoteControllerResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerResetResponse.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerResetResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{5}
}

func (x *NVMfRemoteControllerResetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerResetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerListRequest) Reset() {
	*x = NVMfRemoteControllerListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerListRequest) ProtoMessage() {}

func (x *NVMfRemoteControllerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerListRequest.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerListRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{6}
}

func (x *NVMfRemoteControllerListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerListRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerListResponse) Reset() {
	*x = NVMfRemoteControllerListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerListResponse) ProtoMessage() {}

func (x *NVMfRemoteControllerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerListResponse.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerListResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{7}
}

func (x *NVMfRemoteControllerListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerListResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerGetRequest) Reset() {
	*x = NVMfRemoteControllerGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerGetRequest) ProtoMessage() {}

func (x *NVMfRemoteControllerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerGetRequest.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerGetRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{8}
}

func (x *NVMfRemoteControllerGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerGetResponse) Reset() {
	*x = NVMfRemoteControllerGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerGetResponse) ProtoMessage() {}

func (x *NVMfRemoteControllerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerGetResponse.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerGetResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{9}
}

func (x *NVMfRemoteControllerGetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerGetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerStatsRequest) Reset() {
	*x = NVMfRemoteControllerStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerStatsRequest) ProtoMessage() {}

func (x *NVMfRemoteControllerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerStatsRequest.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerStatsRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{10}
}

func (x *NVMfRemoteControllerStatsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerStatsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NVMfRemoteControllerStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NVMfRemoteControllerStatsResponse) Reset() {
	*x = NVMfRemoteControllerStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NVMfRemoteControllerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMfRemoteControllerStatsResponse) ProtoMessage() {}

func (x *NVMfRemoteControllerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMfRemoteControllerStatsResponse.ProtoReflect.Descriptor instead.
func (*NVMfRemoteControllerStatsResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{11}
}

func (x *NVMfRemoteControllerStatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NVMfRemoteControllerStatsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_backend_proto protoreflect.FileDescriptor

var file_backend_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x22,
	0x48, 0x0a, 0x22, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x23, 0x4e, 0x56, 0x4d,
	0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x25, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x4c, 0x0a, 0x26, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x46, 0x0a, 0x20, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x21, 0x4e, 0x56, 0x4d, 0x66, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x45, 0x0a, 0x1f, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x20, 0x4e, 0x56, 0x4d, 0x66, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x44, 0x0a, 0x1e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x1f, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x20,
	0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x21, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xbe, 0x06,
	0x0a, 0x14, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x88, 0x01, 0x0a, 0x1b, 0x4e, 0x56, 0x4d, 0x66, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x32, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6f, 0x70, 0x69,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x91, 0x01, 0x0a, 0x1e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x12, 0x35, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x6f, 0x70,
	0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d,
	0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x82, 0x01, 0x0a, 0x19, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x12, 0x30, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7f, 0x0a, 0x18, 0x4e, 0x56,
	0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7c, 0x0a, 0x17, 0x4e,
	0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x47, 0x65, 0x74, 0x12, 0x2e, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x82, 0x01, 0x0a, 0x19, 0x4e, 0x56,
	0x4d, 0x66, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x30, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6f, 0x70, 0x69, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x56, 0x4d, 0x66, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2f, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_proto_rawDescOnce sync.Once
	file_backend_proto_rawDescData = file_backend_proto_rawDesc
)

func file_backend_proto_rawDescGZIP() []byte {
	file_backend_proto_rawDescOnce.Do(func() {
		file_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_proto_rawDescData)
	})
	return file_backend_proto_rawDescData
}

var file_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_backend_proto_goTypes = []interface{}{
	(*NVMfRemoteControllerConnectRequest)(nil),     // 0: opi.storage.v1.NVMfRemoteControllerConnectRequest
	(*NVMfRemoteControllerConnectResponse)(nil),    // 1: opi.storage.v1.NVMfRemoteControllerConnectResponse
	(*NVMfRemoteControllerDisconnectRequest)(nil),  // 2: opi.storage.v1.NVMfRemoteControllerDisconnectRequest
	(*NVMfRemoteControllerDisconnectResponse)(nil), // 3: opi.storage.v1.NVMfRemoteControllerDisconnectResponse
	(*NVMfRemoteControllerResetRequest)(nil),       // 4: opi.storage.v1.NVMfRemoteControllerResetRequest
	(*NVMfRemoteControllerResetResponse)(nil),      // 5: opi.storage.v1.NVMfRemoteControllerResetResponse
	(*NVMfRemoteControllerListRequest)(nil),        // 6: opi.storage.v1.NVMfRemoteControllerListRequest
	(*NVMfRemoteControllerListResponse)(nil),       // 7: opi.storage.v1.NVMfRemoteControllerListResponse
	(*NVMfRemoteControllerGetRequest)(nil),         // 8: opi.storage.v1.NVMfRemoteControllerGetRequest
	(*NVMfRemoteControllerGetResponse)(nil),        // 9: opi.storage.v1.NVMfRemoteControllerGetResponse
	(*NVMfRemoteControllerStatsRequest)(nil),       // 10: opi.storage.v1.NVMfRemoteControllerStatsRequest
	(*NVMfRemoteControllerStatsResponse)(nil),      // 11: opi.storage.v1.NVMfRemoteControllerStatsResponse
}
var file_backend_proto_depIdxs = []int32{
	0,  // 0: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerConnect:input_type -> opi.storage.v1.NVMfRemoteControllerConnectRequest
	2,  // 1: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerDisconnect:input_type -> opi.storage.v1.NVMfRemoteControllerDisconnectRequest
	4,  // 2: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerReset:input_type -> opi.storage.v1.NVMfRemoteControllerResetRequest
	6,  // 3: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerList:input_type -> opi.storage.v1.NVMfRemoteControllerListRequest
	8,  // 4: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerGet:input_type -> opi.storage.v1.NVMfRemoteControllerGetRequest
	10, // 5: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerStats:input_type -> opi.storage.v1.NVMfRemoteControllerStatsRequest
	1,  // 6: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerConnect:output_type -> opi.storage.v1.NVMfRemoteControllerConnectResponse
	3,  // 7: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerDisconnect:output_type -> opi.storage.v1.NVMfRemoteControllerDisconnectResponse
	5,  // 8: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerReset:output_type -> opi.storage.v1.NVMfRemoteControllerResetResponse
	7,  // 9: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerList:output_type -> opi.storage.v1.NVMfRemoteControllerListResponse
	9,  // 10: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerGet:output_type -> opi.storage.v1.NVMfRemoteControllerGetResponse
	11, // 11: opi.storage.v1.NVMfRemoteController.NVMfRemoteControllerStats:output_type -> opi.storage.v1.NVMfRemoteControllerStatsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_backend_proto_init() }
func file_backend_proto_init() {
	if File_backend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerDisconnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerDisconnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerResetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NVMfRemoteControllerStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_goTypes,
		DependencyIndexes: file_backend_proto_depIdxs,
		MessageInfos:      file_backend_proto_msgTypes,
	}.Build()
	File_backend_proto = out.File
	file_backend_proto_rawDesc = nil
	file_backend_proto_goTypes = nil
	file_backend_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NVMfRemoteControllerClient is the client API for NVMfRemoteController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NVMfRemoteControllerClient interface {
	NVMfRemoteControllerConnect(ctx context.Context, in *NVMfRemoteControllerConnectRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerConnectResponse, error)
	NVMfRemoteControllerDisconnect(ctx context.Context, in *NVMfRemoteControllerDisconnectRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerDisconnectResponse, error)
	NVMfRemoteControllerReset(ctx context.Context, in *NVMfRemoteControllerResetRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerResetResponse, error)
	NVMfRemoteControllerList(ctx context.Context, in *NVMfRemoteControllerListRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerListResponse, error)
	NVMfRemoteControllerGet(ctx context.Context, in *NVMfRemoteControllerGetRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerGetResponse, error)
	NVMfRemoteControllerStats(ctx context.Context, in *NVMfRemoteControllerStatsRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerStatsResponse, error)
}

type nVMfRemoteControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNVMfRemoteControllerClient(cc grpc.ClientConnInterface) NVMfRemoteControllerClient {
	return &nVMfRemoteControllerClient{cc}
}

func (c *nVMfRemoteControllerClient) NVMfRemoteControllerConnect(ctx context.Context, in *NVMfRemoteControllerConnectRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerConnectResponse, error) {
	out := new(NVMfRemoteControllerConnectResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMfRemoteControllerClient) NVMfRemoteControllerDisconnect(ctx context.Context, in *NVMfRemoteControllerDisconnectRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerDisconnectResponse, error) {
	out := new(NVMfRemoteControllerDisconnectResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerDisconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMfRemoteControllerClient) NVMfRemoteControllerReset(ctx context.Context, in *NVMfRemoteControllerResetRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerResetResponse, error) {
	out := new(NVMfRemoteControllerResetResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMfRemoteControllerClient) NVMfRemoteControllerList(ctx context.Context, in *NVMfRemoteControllerListRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerListResponse, error) {
	out := new(NVMfRemoteControllerListResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMfRemoteControllerClient) NVMfRemoteControllerGet(ctx context.Context, in *NVMfRemoteControllerGetRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerGetResponse, error) {
	out := new(NVMfRemoteControllerGetResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMfRemoteControllerClient) NVMfRemoteControllerStats(ctx context.Context, in *NVMfRemoteControllerStatsRequest, opts ...grpc.CallOption) (*NVMfRemoteControllerStatsResponse, error) {
	out := new(NVMfRemoteControllerStatsResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NVMfRemoteControllerServer is the server API for NVMfRemoteController service.
type NVMfRemoteControllerServer interface {
	NVMfRemoteControllerConnect(context.Context, *NVMfRemoteControllerConnectRequest) (*NVMfRemoteControllerConnectResponse, error)
	NVMfRemoteControllerDisconnect(context.Context, *NVMfRemoteControllerDisconnectRequest) (*NVMfRemoteControllerDisconnectResponse, error)
	NVMfRemoteControllerReset(context.Context, *NVMfRemoteControllerResetRequest) (*NVMfRemoteControllerResetResponse, error)
	NVMfRemoteControllerList(context.Context, *NVMfRemoteControllerListRequest) (*NVMfRemoteControllerListResponse, error)
	NVMfRemoteControllerGet(context.Context, *NVMfRemoteControllerGetRequest) (*NVMfRemoteControllerGetResponse, error)
	NVMfRemoteControllerStats(context.Context, *NVMfRemoteControllerStatsRequest) (*NVMfRemoteControllerStatsResponse, error)
}

// UnimplementedNVMfRemoteControllerServer can be embedded to have forward compatible implementations.
type UnimplementedNVMfRemoteControllerServer struct {
}

func (*UnimplementedNVMfRemoteControllerServer) NVMfRemoteControllerConnect(context.Context, *NVMfRemoteControllerConnectRequest) (*NVMfRemoteControllerConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NVMfRemoteControllerConnect not implemented")
}
func (*UnimplementedNVMfRemoteControllerServer) NVMfRemoteControllerDisconnect(context.Context, *NVMfRemoteControllerDisconnectRequest) (*NVMfRemoteControllerDisconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NVMfRemoteControllerDisconnect not implemented")
}
func (*UnimplementedNVMfRemoteControllerServer) NVMfRemoteControllerReset(context.Context, *NVMfRemoteControllerResetRequest) (*NVMfRemoteControllerResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NVMfRemoteControllerReset not implemented")
}
func (*UnimplementedNVMfRemoteControllerServer) NVMfRemoteControllerList(context.Context, *NVMfRemoteControllerListRequest) (*NVMfRemoteControllerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NVMfRemoteControllerList not implemented")
}
func (*UnimplementedNVMfRemoteControllerServer) NVMfRemoteControllerGet(context.Context, *NVMfRemoteControllerGetRequest) (*NVMfRemoteControllerGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NVMfRemoteControllerGet not implemented")
}
func (*UnimplementedNVMfRemoteControllerServer) NVMfRemoteControllerStats(context.Context, *NVMfRemoteControllerStatsRequest) (*NVMfRemoteControllerStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NVMfRemoteControllerStats not implemented")
}

func RegisterNVMfRemoteControllerServer(s *grpc.Server, srv NVMfRemoteControllerServer) {
	s.RegisterService(&_NVMfRemoteController_serviceDesc, srv)
}

func _NVMfRemoteController_NVMfRemoteControllerConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NVMfRemoteControllerConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerConnect(ctx, req.(*NVMfRemoteControllerConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMfRemoteController_NVMfRemoteControllerDisconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NVMfRemoteControllerDisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerDisconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerDisconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerDisconnect(ctx, req.(*NVMfRemoteControllerDisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMfRemoteController_NVMfRemoteControllerReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NVMfRemoteControllerResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerReset(ctx, req.(*NVMfRemoteControllerResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMfRemoteController_NVMfRemoteControllerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NVMfRemoteControllerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerList(ctx, req.(*NVMfRemoteControllerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMfRemoteController_NVMfRemoteControllerGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NVMfRemoteControllerGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerGet(ctx, req.(*NVMfRemoteControllerGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMfRemoteController_NVMfRemoteControllerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NVMfRemoteControllerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NVMfRemoteController/NVMfRemoteControllerStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMfRemoteControllerServer).NVMfRemoteControllerStats(ctx, req.(*NVMfRemoteControllerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NVMfRemoteController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opi.storage.v1.NVMfRemoteController",
	HandlerType: (*NVMfRemoteControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NVMfRemoteControllerConnect",
			Handler:    _NVMfRemoteController_NVMfRemoteControllerConnect_Handler,
		},
		{
			MethodName: "NVMfRemoteControllerDisconnect",
			Handler:    _NVMfRemoteController_NVMfRemoteControllerDisconnect_Handler,
		},
		{
			MethodName: "NVMfRemoteControllerReset",
			Handler:    _NVMfRemoteController_NVMfRemoteControllerReset_Handler,
		},
		{
			MethodName: "NVMfRemoteControllerList",
			Handler:    _NVMfRemoteController_NVMfRemoteControllerList_Handler,
		},
		{
			MethodName: "NVMfRemoteControllerGet",
			Handler:    _NVMfRemoteController_NVMfRemoteControllerGet_Handler,
		},
		{
			MethodName: "NVMfRemoteControllerStats",
			Handler:    _NVMfRemoteController_NVMfRemoteControllerStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
