---
name: Docker

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  call:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: opiproject/actions/.github/workflows/docker-publish.yml@main
    secrets: inherit
