name: 'OPI Storage PoC CI'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-storage-skip-${{ github.ref }}
  cancel-in-progress: true

jobs:
  storage-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - server
          - client
    steps:
      - run: 'echo "No storage POC test run required"'

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No storage POC test run required"'
