name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-docker:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
